### ISSUE TITLE
error in calcBins

### ISSUE THREAD

**Issue by gsudre** [JMF47/MDTS#1]
Hello,

This tools looks quite interesting! I'm getting an error when I try to use it in my trio data:

> genome = BSgenome.Hsapiens.UCSC.hg19; map_file = "chr1.map.bw"
> bins = calcBins(pD, n=5, med=150, min=5, genome, map_file)
Reading coverage information of subsamples
BAM/CLIA_400188.bam
BAM/CLIA_400137.bam
BAM/CLIA_400121.bam
BAM/CLIA_400122.bam
BAM/CLIA_400171.bam
Calculating Proto-regions
Selecting Proto-regions in Chr 1
Error in t(proto_gr_covs_mat)/rl :
  non-numeric argument to binary operator

Any ideas of what's going on?

Thanks!

Gustavo

**Comment by JMF47** [comment]
If installing the package line I provided in the other issue doesn't help with this, could you let me know the `traceback()` and I can try and narrow it down? Thanks!

**Comment by gsudre** [comment]
> bins = calcBins(pD, n=5, med=150, min=5, genome, map_file)
Reading coverage information of subsamples
BAM/CLIA_400188.bam
BAM/CLIA_400137.bam
BAM/CLIA_400121.bam
BAM/CLIA_400122.bam
BAM/CLIA_400171.bam
Calculating Proto-regions
Selecting Proto-regions in Chr 1
Error in t(proto_gr_covs_mat)/rl :
  non-numeric argument to binary operator
> traceback()
4: t(t(proto_gr_covs_mat)/rl)
3: FUN(X[[i]], ...)
2: lapply(seq_len(22), .processChr, rle_track0, covs, readLength, 
       medianCoverage)
1: calcBins(pD, n = 5, med = 150, min = 5, genome, map_file)
>

Let me know if I can provide more details.

**Comment by JMF47** [comment]
Thanks for the info! It appears that you are missing an argument in the function call.
Could you try:
```
bins = calcBins(metaData=pD, n=5, **readLength=YOUR_READ_LENGTH**, 
    medianCoverage=150, minimumCoverage=5,
    genome=genome, mappabilityFile=map_file)
```
with the read length from your sequencing study?

Thanks! This is a good reminder for me to build in more unit tests and I/O checks. :)

**Comment by gsudre** [comment]
Yep, that did it. Thanks!
