### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gsudre** [JMF47/MDTS#2]
Hello,

This is unrelated to the previous issue I opened. When I try to install the tool, I get an error that it requires R >= 3.5, but that version is not even out yet?

I'm getting by just downloading the individual scripts, but I wanted to bring it to your attention!

Thanks,

Gustavo

**Comment by JMF47** [comment]
Hi Gustavo, thanks for the interest. As part of the bioconductor submission process one of the requirements is to require the soon to be released R version. I’m going to create a new branch with R3.4 for you to use. I will link it here. I suspect the error you saw in the previous issue might be a namespace issue from not installing the package.

**Comment by JMF47** [comment]
Hi @gsudre, try installing now with the command:
```
install_github('jmf47/MDTS', ref="R-3.4", build_vignettes=TRUE)
```
I've also updated the argument names slightly in the vignette to be more clear.
Let me know how it goes!

Best,
Jack

**Comment by gsudre** [comment]
Jack,

Thanks for getting back to me. The install works now, but the other issue is still there. I'll address it in the other issue.
